apiVersion: v1
kind: Service
metadata:
  labels:
    app: thanos-query
    part-of: {{ .Values.namespace }}
  name: thanos-query
  namespace: {{ .Values.namespace }}
spec:
  type: LoadBalancer
  ports:
  - name: grpc
    port: 10901
    targetPort: grpc
  - name: http
    port: 9090
    targetPort: http
  selector:
    app: thanos-query
    part-of: {{ .Values.namespace }}