apiVersion: v1
kind: Service
metadata:
  labels:
    app: thanos-store
    shard: shard-0
    tenant: a
    part-of: {{ .Values.namespace }}
  name: thanos-store-shard-0
  namespace: {{ .Values.namespace }}
spec:
  clusterIP: None
  ports:
  - name: grpc
    port: 10901
    targetPort: 10901
  - name: http
    port: 10902
    targetPort: 10902
  selector:
    app: thanos-store
    shard: shard-0
    tenant: a
    part-of: {{ .Values.namespace }}
