apiVersion: v1
kind: Secret
metadata:
  name: thanos-objectstorage
  namespace: {{ .Values.namespace }}
  labels:
    part-of: {{ .Values.namespace }}
type: Opaque
data:
  bucket: {{ default "" .Values.thanos.s3Configurations.bucket | b64enc | quote }}
  password: {{ default "" .Values.thanos.s3Configurations.region | b64enc | quote }}