apiVersion: v1
kind: Secret
metadata:
  name: thanos-objectstorage
  namespace: {{ .Values.namespace }}
  labels:
    part-of: {{ .Values.namespace }}
type: Opaque
data:
  thanos-s3.yaml: |-
    type: S3
    config:
      bucket: {{ default "" .Values.thanos.s3Configurations.bucket | quote }}
      endpoint: "s3.amazonaws.com"
      region: {{ default "" .Values.thanos.s3Configurations.region | quote }}
      insecure: true
