apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: thanos-query
    part-of: {{ .Values.namespace }}
  name: thanos-query
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thanos-query
      part-of: {{ .Values.namespace }}
  template:
    metadata:
      labels:
        app: thanos-query
        part-of: {{ .Values.namespace }}
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - thanos-query
              namespaces:
              - observatorium
              topologyKey: kubernetes.io/hostname
            weight: 100
      containers:
      - args:
        - query
        - --log.level=info
        - --grpc-address=0.0.0.0:10901
        - --http-address=0.0.0.0:9090
        - --query.replica-label=prometheus_replica
        - --query.replica-label=receive_replica
        - --store=dnssrv+_grpc._tcp.thanos-store-shard-0.{{ .Values.namespace }}.svc.cluster.local
        - --store=dnssrv+_grpc._tcp.thanos-receive-default.{{ .Values.namespace }}.svc.cluster.local
          #- --store=dnssrv+_grpc._tcp.thanos-receive-hashring-0.thanos.svc.cluster.local
        - --query.timeout=15m
        image: quay.io/thanos/thanos:v0.23.1
        livenessProbe:
          failureThreshold: 4
          httpGet:
            path: /-/healthy
            port: 9090
            scheme: HTTP
          periodSeconds: 30
        name: thanos-query
        ports:
        - containerPort: 10901
          name: grpc
        - containerPort: 9090
          name: http
        readinessProbe:
          failureThreshold: 20
          httpGet:
            path: /-/ready
            port: 9090
            scheme: HTTP
          periodSeconds: 5
        terminationMessagePolicy: FallbackToLogsOnError
      terminationGracePeriodSeconds: 120