apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: thanos-receive-controller
    part-of: {{ .Values.namespace }}
  name: thanos-receive-controller
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thanos-receive-controller
      part-of: {{ .Values.namespace }}
  template:
    metadata:
      labels:
        app: thanos-receive-controller
        part-of: {{ .Values.namespace }}
    spec:
      containers:
      - args:
        - --configmap-name=thanos-receive-base
        - --configmap-generated-name=thanos-receive-generated
        - --file-name=hashrings.json
        - --namespace={{ .Values.namespace }}
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: quay.io/observatorium/thanos-receive-controller:latest
        name: thanos-receive-controller
        ports:
        - containerPort: 8080
          name: http
      serviceAccount: thanos-receive-controller
